import { flags } from "@oclif/command";
import { BaseCommand } from "../BaseCommand";
export default class MachinesList extends BaseCommand {
    static flags: {
        "machineId": flags.IOptionFlag<string | undefined>;
        "name": flags.IOptionFlag<string | undefined>;
        "os": flags.IOptionFlag<string | undefined>;
        "ram": flags.IOptionFlag<string | undefined>;
        "cpus": import("@oclif/parser/lib/flags").IOptionFlag<number | undefined>;
        "gpu": flags.IOptionFlag<string | undefined>;
        "storageTotal": flags.IOptionFlag<string | undefined>;
        "storageUsed": flags.IOptionFlag<string | undefined>;
        "usageRate": flags.IOptionFlag<string | undefined>;
        "shutdownTimeoutInHours": import("@oclif/parser/lib/flags").IOptionFlag<number | undefined>;
        "performAutoSnapshot": import("@oclif/parser/lib/flags").IBooleanFlag<boolean>;
        "autoSnapshotFrequency": flags.IOptionFlag<string | undefined>;
        "autoSnapshotSaveCount": import("@oclif/parser/lib/flags").IOptionFlag<number | undefined>;
        "agentType": flags.IOptionFlag<string | undefined>;
        "dtCreated": flags.IOptionFlag<string | undefined>;
        "state": flags.IOptionFlag<string | undefined>;
        "updatesPending": import("@oclif/parser/lib/flags").IBooleanFlag<boolean>;
        "networkId": flags.IOptionFlag<string | undefined>;
        "privateIpAddress": flags.IOptionFlag<string | undefined>;
        "publicIpAddress": flags.IOptionFlag<string | undefined>;
        "region": flags.IOptionFlag<string | undefined>;
        "userId": flags.IOptionFlag<string | undefined>;
        "teamId": flags.IOptionFlag<string | undefined>;
        "scriptId": flags.IOptionFlag<string | undefined>;
        "dtLastRun": flags.IOptionFlag<string | undefined>;
    };
    run(): Promise<import("@paper/paper-api").ResponseWithBody<{
        agentType?: string | undefined;
        autoSnapshotFrequency?: number | undefined;
        autoSnapshotSaveCount?: number | undefined;
        cpus?: number | undefined;
        dtCreated?: string | undefined;
        dtLastRun?: string | undefined;
        dynamicPublicIp?: string | undefined;
        gpu?: string | undefined;
        id?: string | undefined;
        name?: string | undefined;
        networkId?: string | undefined;
        os?: string | undefined;
        performAutoSnapshot?: boolean | undefined;
        privateIpAddress?: string | undefined;
        publicIpAddress?: string | undefined;
        ram?: string | undefined;
        region?: string | undefined;
        scriptId?: string | undefined;
        shutdownTimeoutForces?: boolean | undefined;
        shutdownTimeoutInHours?: number | undefined;
        state?: string | undefined;
        storageTotal?: string | undefined;
        storageUsed?: string | undefined;
        teamId?: string | undefined;
        updatesPending?: boolean | undefined;
        usageRate?: string | undefined;
        userId?: string | undefined;
    }[]>>;
}
